### ISSUE TITLE
Choix du jeu

### ISSUE THREAD

**Issue by Tiphaniiie** [TelecomLille-INFO/fa18-projet1#1]
Décision à prendre de préférence aujourd'hui (25/02/16)

**Comment by BenjaminGuilbert** [comment]
Tout à fait!!

**Comment by Tiphaniiie** [comment]
Donc je mets l'idée que j'ai ici, histoire qu'on ait une trace.

Jeu style RPG
But : le héros doit passer les portes des niveaux pour tuer le boss final (par exemple, ou devenir très riche, comme vous le sentez).
Comment ?
Une clé est cachée dans le niveau, il faut la trouver pour passer le portail.
Gameplay : 
On avance avec les flèches, et on subit des rencontres aléatoires avec des monstres (ou des trucs plus drôles à combattre). Les loots nous donnent des armures, des potions (pas de sous, trop long à implémenter s'il y a des marchands).
Combat : on a genre 3 skills de base, qu'on peut augmenter avec l'expérience (magie, physique, défense ?) Donc 3 types de monstres : sensibles à la magie, au physique, ou qui attaquent très fort.
EDIT: J'ai oublié de préciser que ce serait du tour par tour.
Sur la map principale : accès à l'inventaire (armures, potions), et au perso (vision du perso, son lvl, choix pour up les skills).

Et puis voilà, je pense que ça serait pas super compliqué à mettre en place, au niveau des règles. Si on a le temps, on pourrait affiner un peu plus, sinon, on simplifie si on est à la bourre.

**Comment by ayoubel** [comment]
Très bien ! Le plus important pour une première Release est qu'on aie une petite démo ( plateau,une premiere map,un gogole qui court, qui combat avec meme un seule skill de base). Si on code ça PROPREMENT, je suis sûr que tout va bien se dérouler derrière et rapidement.

Le plus important :+1: Se répartir les taches !!
