### ISSUE TITLE
problème pour committer 

### ISSUE THREAD

**Issue by BenjaminGuilbert** [TelecomLille-INFO/fa18-projet1#3]
Pas moyen de committer des fichiers dans ce projet

<img width="572" alt="capture d ecran 2016-02-29 a 11 08 38" src="https://cloud.githubusercontent.com/assets/16096766/13391799/c29aa60a-ded6-11e5-823f-e3028816039b.png">

je ne comprends pas... à l'aide

**Comment by cdlm** [comment]
On dirait que ta remote est mal configurée. Dis-nous ce que répond `git remote show origin`.

**Comment by BenjaminGuilbert** [comment]
oui j'avais oublié de faire git remote add origin https://github.com/TelecomLille-INFO/fa18-projet1.git
merci
